using Kapa.Abstractions.BDD;
using Kapa.Core.BDD;
using Kapa.Core.Extensions;

namespace HomeAutomation.Capabilities;

// TODO: THIS IS JUST AN EXAMPLE FOR AUTOGENERATED EXTENSION METHODS
public static class ScenarioBuilderExtensions
{
    public static IScenarioBuilder AddLight(
        this IScenarioBuilder scenarioBuilder,
        IUser user,
        string lightName,
        string model
    )
    {
        ArgumentNullException.ThrowIfNull(scenarioBuilder);

        /*
         * User (and other things) can be injected inside DomoticCapabilities so
         * need a better way than GetCapabilityType.
         *
         * Should enforce that CapabilityType like Endpoint are singleton.
         * Therefor pass IUser to the Capability.
         *
         * Should probably take example on minimal api and makes the difference between what is injected
         * in the method and what is injected in the handler class (Add Interface ICapabilityHandler ?)
        https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-9.0
         */

        //
        var capabilityType = scenarioBuilder.GetCapabilityType<DomoticCapabilities>();
        var capability = typeof(DomoticCapabilities)
            .GetCapabilities()
            .Where(c => c.Name == nameof(AddLight))
            .First();

        IKapaStep step = new KapaStep(
            user,
            capability,
            async (ct) => await capabilityType.AddLight(user, lightName, model, ct)
        );

        scenarioBuilder.AddSteps(step);
        return scenarioBuilder;
    }
}
