---
config:
  layout: elk
---
graph TD
SetThermostatSetpoint["SetThermostatSetpoint<br/>'Change the Thermostat Setpoint.' "]
Setup["Setup<br/>'Setup the User.' "]
AuthenticateAsync["AuthenticateAsync<br/>'Authenticate the User.' "]
Setup -->|"The IUser is authenticated.<br/>Has Thermostat"| SetThermostatSetpoint
AuthenticateAsync -->|"The IUser is authenticated."| SetThermostatSetpoint
