---
config:
  layout: elk
---
graph TD
AuthenticateAsync["AuthenticateAsync<br/>'Authenticate the User.' "]
SwitchLight["SwitchLight<br/>'Change the Light IsOn state.' "]
SetThermostatSetpoint["SetThermostatSetpoint<br/>'Change the Thermostat Setpoint.' "]
AddThermostat["AddThermostat<br/>'Add a Thermostat to the Home.' "]
AddLight["AddLight<br/>'Add a Light to the Home.' "]
Setup["Setup<br/>'Setup the User.' "]
AuthenticateAsync -->|"The IUser is authenticated. [1]"| SwitchLight
AddLight -->|"The IUser's Home has at least 1 Light. [2]"| SwitchLight
Setup -->|"The IUser's Home has at least 1 Light. [3]"| SwitchLight
AuthenticateAsync -->|"The IUser is authenticated. [4]"| SetThermostatSetpoint
AddThermostat -->|"The IUser's Home has at least 1 Thermostat. [5]"| SetThermostatSetpoint
Setup -->|"The IUser's Home has at least 1 Thermostat. [6]"| SetThermostatSetpoint
AuthenticateAsync -->|"The IUser is authenticated. [7]"| AddThermostat
AuthenticateAsync -->|"The IUser is authenticated. [8]"| AddLight
