---
config:
  layout: elk
---
graph TD
SwitchLight["SwitchLight<br/>'Change the Light IsOn state.' "]
AuthenticateAsync["AuthenticateAsync<br/>'Authenticate the User.' "]
Setup["Setup<br/>'Setup the User.' "]
AddLight["AddLight<br/>'Add a Light to the Home.' "]
AuthenticateAsync -->|"The IUser is authenticated."| SwitchLight
Setup -->|"The IUser is authenticated.<br/>The IUser's Home has at least 1 Light."| SwitchLight
AddLight -->|"The IUser's Home has at least 1 Light."| SwitchLight
AuthenticateAsync -->|"The IUser is authenticated."| AddLight
Setup -->|"The IUser is authenticated."| AddLight
