---
config:
  layout: elk
---
graph TD
SwitchLight["SwitchLight<br/>'Change the Light IsOn state.' <br/>✅ The IUser is authenticated. [1, 2, 5, 6]<br/>✅ The IUser's Home has at least 1 Light. [3, 4]"]
AuthenticateAsync["AuthenticateAsync<br/>'Authenticate the User.' "]
Setup["Setup<br/>'Setup the User.' "]
AddLight["AddLight<br/>'Add a Light to the Home.' <br/>✅ The IUser is authenticated. [5, 6]"]
AuthenticateAsync -->|"The IUser is authenticated. [1]"| SwitchLight
Setup -->|"The IUser is authenticated. [2]<br/>The IUser's Home has at least 1 Light. [3]"| SwitchLight
AddLight -->|"The IUser's Home has at least 1 Light. [4]"| SwitchLight
AuthenticateAsync -->|"The IUser is authenticated. [5]"| AddLight
Setup -->|"The IUser is authenticated. [6]"| AddLight
